FROM node:lts-alpine

ENV NODE_ENV=production
ENV REACT_APP_IPINFO_API_KEY=${REACT_APP_IPINFO_API_KEY}
ENV REACT_APP_GOOGLE_SAFE_BROWSING_API_KEY=${REACT_APP_GOOGLE_SAFE_BROWSING_API_KEY}
ENV REACT_APP_VIRUS_TOTAL_API_KEY=${REACT_APP_GOOGLE_SAFE_BROWSING_API_KEY}
ENV REACT_APP_LINKPREVIEW_API_KEY=${REACT_APP_LINKPREVIEW_API_KEY}
ENV REACT_APP_SCRAPER_API_KEY=${REACT_APP_SCRAPER_API_KEY}

WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
